import Sidebar from '../components/Sidebar';
import { RevenueAreaChart, CategoryBarChart } from '../components/RevenueChart';
import { useData } from '../context/DataContext';
import {
  TrendingUp, CheckCircle2, Lightbulb,
  Download, Share2, FileText, ExternalLink,
  BarChart2, Target, FileSpreadsheet, MessageSquare
} from 'lucide-react';
import { Link } from 'react-router-dom';

const INSIGHT_COLORS = [
  { bg: 'rgba(16,185,129,0.1)',  color: '#10b981' },
  { bg: 'rgba(59,130,246,0.1)',  color: '#3b82f6' },
  { bg: 'rgba(245,158,11,0.1)',  color: '#f59e0b' },
  { bg: 'rgba(239,68,68,0.1)',   color: '#ef4444' },
  { bg: 'rgba(99,102,241,0.1)',  color: '#818cf8' },
  { bg: 'rgba(59,130,246,0.1)', color: '#60a5fa' },
];

function EmptyState() {
  return (
    <div className="no-data-placeholder">
      <FileText size={48} color="var(--text-muted)" />
      <h3>No AI report generated yet</h3>
      <p>Upload an Excel or CSV file on the Chat page. DeepSeek-R1-32B will analyze it and generate insights, recommendations, and charts here.</p>
      <Link to="/chat">
        <button className="btn-primary" style={{ marginTop: 8, gap: 6 }}>
          <MessageSquare size={14} /> Go to Chat & Upload File
        </button>
      </Link>
    </div>
  );
}

export default function Reports() {
  const { uploadedData } = useData();

  const handleExportPDF = () => {
    window.print();
  };

  const handleDownloadReportText = () => {
    if (!uploadedData) return;
    
    const content = [
      `AI BUSINESS REPORT: ${uploadedData.fileName}`,
      `Generated by ${uploadedData.model || 'DeepSeek-R1-32B'} from ${uploadedData.rowCount.toLocaleString()} rows and ${uploadedData.columns.length} columns`,
      `=========================================`,
      ``,
      `EXECUTIVE SUMMARY:`,
      uploadedData.summary,
      ``,
      `=========================================`,
      `KEY INSIGHTS:`,
      ...(uploadedData.insights || []).map((ins, idx) => `${idx + 1}. ${ins}`),
      ``,
      `=========================================`,
      `RECOMMENDATIONS:`,
      ...(uploadedData.recommendations || []).map((rec, idx) => `${idx + 1}. ${rec.title}: ${rec.desc}`),
      ``,
      `=========================================`,
      `DATASET OVERVIEW:`,
      `- File Name: ${uploadedData.fileName}`,
      `- Total Rows: ${uploadedData.rowCount}`,
      `- Total Columns: ${uploadedData.columns.length}`,
      `- Columns: ${uploadedData.columns.join(', ')}`,
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `dsi_report_${uploadedData.fileName.replace(/\.[^/.]+$/, "")}.txt`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!uploadedData) {
    return (
      <div className="app-layout">
        <Sidebar />
        <main className="main-content">
          <div className="page-header">
            <div>
              <h1 className="page-title">AI Business Report</h1>
              <p className="page-subtitle">Upload your data to generate a report</p>
            </div>
          </div>
          <EmptyState />
        </main>
      </div>
    );
  }

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">

        {/* Data Banner */}
        <div className="data-banner">
          <FileSpreadsheet size={15} />
          <span>AI Report from:</span>
          <span className="data-banner-file">{uploadedData.fileName}</span>
          <span className="data-banner-meta">
            · {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.model || 'DeepSeek-R1-32B'}
          </span>
          <Link to="/chat" style={{ marginLeft: 'auto' }}>
            <button className="btn-outline" style={{ fontSize: 11, padding: '4px 10px', gap: 4 }}>
              <MessageSquare size={11} /> Ask AI
            </button>
          </Link>
        </div>

        {/* Header */}
        <div className="page-header">
          <div>
            <h1 className="page-title">AI Report · {uploadedData.fileName}</h1>
            <p className="page-subtitle">
              Generated by {uploadedData.model || 'DeepSeek-R1-32B'} from {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.columns.length} columns
            </p>
          </div>
          <div className="page-actions">
            <Link to="/report/shared">
              <button className="btn-outline" style={{ gap: 6, fontSize: 13 }}>
                <ExternalLink size={13} /> Share Report
              </button>
            </Link>
            <button className="btn-primary" onClick={handleExportPDF} style={{ gap: 6, fontSize: 13 }}>
              <Download size={13} /> Export PDF
            </button>
          </div>
        </div>

        {/* Executive Summary Banner */}
        <div className="report-hero animate-fadeInUp">
          <div className="report-meta">
            <span className="badge badge-blue"><FileText size={11} /> AI Generated</span>
            <span className="badge badge-green"><CheckCircle2 size={11} /> Auto-analyzed</span>
            <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              File: {uploadedData.fileName} · {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.model || 'DeepSeek-R1-32B'}
            </span>
          </div>
          <h2 className="report-title">Data Analysis Report · {uploadedData.fileName}</h2>
          <p className="report-summary">{uploadedData.summary}</p>
        </div>

        {/* AI Insights Grid */}
        {uploadedData.insights?.length > 0 && (
          <>
            <div style={{ fontSize: 13, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Lightbulb size={14} color="var(--blue-400)" />
              Key Insights from {uploadedData.model || 'DeepSeek-R1-32B'}
            </div>
            <div className="insights-grid animate-fadeInUp" style={{ animationDelay: '0.1s' }}>
              {uploadedData.insights.map((text, i) => {
                const { bg, color } = INSIGHT_COLORS[i % INSIGHT_COLORS.length];
                return (
                  <div key={i} className="insight-card" style={{ animationDelay: `${i * 0.07}s` }}>
                    <div className="insight-icon" style={{ background: bg }}>
                      <TrendingUp size={18} color={color} />
                    </div>
                    <div className="insight-label">Insight {i + 1}</div>
                    <div className="insight-desc">{text}</div>
                  </div>
                );
              })}
            </div>
          </>
        )}

        {/* Charts */}
        {(uploadedData.trendData?.length > 0 || uploadedData.chartData?.length > 0) && (
          <div className="chart-grid animate-fadeInUp" style={{ animationDelay: '0.2s' }}>
            {uploadedData.trendData?.length > 0 && (
              <div className="chart-card">
                <div className="chart-card-header">
                  <div>
                    <div className="chart-card-title">Revenue Trend</div>
                    <div className="chart-card-subtitle">From {uploadedData.fileName}</div>
                  </div>
                </div>
                <RevenueAreaChart data={uploadedData.trendData} />
              </div>
            )}
            {uploadedData.chartData?.length > 0 && (
              <div className="chart-card">
                <div className="chart-card-header">
                  <div>
                    <div className="chart-card-title">Category Breakdown</div>
                    <div className="chart-card-subtitle">AI-extracted segments</div>
                  </div>
                </div>
                <CategoryBarChart data={uploadedData.chartData} />
              </div>
            )}
          </div>
        )}

        {/* AI Recommendations */}
        {uploadedData.recommendations?.length > 0 && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.3s' }}>
            <div className="report-section-title">
              <Target size={18} color="var(--blue-400)" />
              {uploadedData.model || 'DeepSeek-R1-32B'} Recommendations
            </div>
            <div className="recommendations-list">
              {uploadedData.recommendations.map((r, i) => (
                <div key={i} className="recommendation-item">
                  <div className="recommendation-num">{i + 1}</div>
                  <div>
                    <div className="recommendation-title">{r.title}</div>
                    <div className="recommendation-desc">{r.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Data columns info */}
        <div className="report-section" style={{ marginTop: 8 }}>
          <div className="report-section-title">
            <BarChart2 size={18} color="var(--blue-400)" />
            Dataset Overview
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16, marginBottom: 16 }}>
            {[
              { label: 'Total Rows',    value: uploadedData.rowCount.toLocaleString() },
              { label: 'Columns',       value: uploadedData.columns.length },
              { label: 'File',          value: uploadedData.fileName },
            ].map(({ label, value }) => (
              <div key={label} style={{ padding: '14px 18px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)' }}>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>{label}</div>
                <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--text-primary)' }}>{value}</div>
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {uploadedData.columns.map(col => (
              <span key={col} className="column-badge">{col}</span>
            ))}
          </div>
        </div>

        {/* Footer Actions */}
        <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end', marginTop: 8, paddingBottom: 24 }}>
          <Link to="/report/shared">
            <button className="btn-outline" style={{ gap: 6 }}>
              <Share2 size={14} /> Share as Live Link
            </button>
          </Link>
          <button className="btn-primary" onClick={handleDownloadReportText} style={{ gap: 6 }}>
            <Download size={14} /> Download Full Report
          </button>
        </div>

      </main>
    </div>
  );
}