import Sidebar from '../components/Sidebar';
import { RevenueAreaChart, CategoryBarChart } from '../components/RevenueChart';
import { useData } from '../context/DataContext';
import {
  TrendingUp, CheckCircle2, Lightbulb,
  Download, Share2, FileText, ExternalLink,
  BarChart2, Target, FileSpreadsheet, MessageSquare, AlertTriangle, AlertCircle,
  Activity
} from 'lucide-react';
import { Link } from 'react-router-dom';

const INSIGHT_COLORS = [
  { bg: 'rgba(16,185,129,0.1)',  color: '#10b981' },
  { bg: 'rgba(59,130,246,0.1)',  color: '#3b82f6' },
  { bg: 'rgba(245,158,11,0.1)',  color: '#f59e0b' },
  { bg: 'rgba(239,68,68,0.1)',   color: '#ef4444' },
  { bg: 'rgba(99,102,241,0.1)',  color: '#818cf8' },
  { bg: 'rgba(59,130,246,0.1)', color: '#60a5fa' },
];

function EmptyState() {
  return (
    <div className="no-data-placeholder">
      <FileText size={48} color="var(--text-muted)" />
      <h3>No AI report generated yet</h3>
      <p>Upload an Excel or CSV file on the Dashboard. Google Gemini 2.5 Flash will automatically analyze it and generate dynamic KPIs, insights, strengths, weaknesses, and recommendations here.</p>
      <Link to="/dashboard">
        <button className="btn-primary" style={{ marginTop: 8, gap: 6 }}>
          <FileSpreadsheet size={14} /> Go to Dashboard
        </button>
      </Link>
    </div>
  );
}

export default function Reports() {
  const { uploadedData } = useData();

  const handleExportPDF = () => {
    window.print();
  };

  const handleDownloadReportText = () => {
    if (!uploadedData) return;
    
    const content = [
      `AI BUSINESS REPORT: ${uploadedData.fileName}`,
      `Dataset Classification: ${uploadedData.datasetType}`,
      `Generated by ${uploadedData.model || 'Gemini-2.5-Flash'} from ${uploadedData.rowCount.toLocaleString()} rows and ${uploadedData.columns.length} columns`,
      `=========================================`,
      ``,
      `1. EXECUTIVE SUMMARY:`,
      uploadedData.summary,
      ``,
      `=========================================`,
      `2. DATASET OVERVIEW:`,
      `- File Name: ${uploadedData.fileName}`,
      `- Total Rows: ${uploadedData.rowCount}`,
      `- Total Columns: ${uploadedData.columns.length}`,
      `- Columns: ${uploadedData.columns.join(', ')}`,
      ``,
      `=========================================`,
      `3. KEY KPIS:`,
      ...(uploadedData.kpis || []).map(k => `- ${k.label}: ${k.value} (${k.desc})`),
      ``,
      `=========================================`,
      `4. KEY INSIGHTS:`,
      ...(uploadedData.insights || []).map((ins, idx) => `${idx + 1}. ${ins}`),
      ``,
      `=========================================`,
      `5. RECOMMENDATIONS:`,
      ...(uploadedData.recommendations || []).map((rec, idx) => `${idx + 1}. ${rec.title}: ${rec.desc}`),
      ``,
      `=========================================`,
      `6. RISKS:`,
      ...(uploadedData.risks || []).map((r, idx) => `- ${r}`),
      ``,
      `=========================================`,
      `7. STRENGTHS:`,
      ...(uploadedData.strengths || []).map((s, idx) => `- ${s}`),
      ``,
      `=========================================`,
      `8. WEAKNESSES:`,
      ...(uploadedData.weaknesses || []).map((w, idx) => `- ${w}`),
      ``,
      `=========================================`,
      `9. FUTURE OPPORTUNITIES:`,
      ...(uploadedData.opportunities || []).map((o, idx) => `- ${o}`),
      ``,
      `=========================================`,
      `10. DATA ANOMALIES:`,
      ...(uploadedData.anomalies || []).map((anom, idx) => `${idx + 1}. ${anom}`),
      ``,
      `=========================================`,
      `11. CONCLUSION:`,
      uploadedData.conclusion,
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `dsi_report_${uploadedData.fileName.replace(/\.[^/.]+$/, "")}.txt`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!uploadedData) {
    return (
      <div className="app-layout">
        <Sidebar />
        <main className="main-content">
          <div className="page-header">
            <div>
              <h1 className="page-title">AI Business Report</h1>
              <p className="page-subtitle">Upload your data to generate a report</p>
            </div>
          </div>
          <EmptyState />
        </main>
      </div>
    );
  }

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">

        {/* Printable optimization styles */}
        <style>{`
          @media print {
            body {
              background: white !important;
              color: black !important;
            }
            .sidebar {
              display: none !important;
            }
            .main-content {
              margin-left: 0 !important;
              padding: 0 !important;
              width: 100% !important;
            }
            .page-actions, .data-banner, .footer-actions, button {
              display: none !important;
            }
            .report-hero {
              border: 1px solid #ccc !important;
              background: #f9f9f9 !important;
              color: black !important;
              padding: 20px !important;
            }
            .report-section, .chart-card {
              border: 1px solid #ccc !important;
              background: white !important;
              color: black !important;
              page-break-inside: avoid;
              margin-bottom: 20px !important;
            }
            .badge, .column-badge {
              border: 1px solid #666 !important;
              color: black !important;
              background: transparent !important;
            }
          }
        `}</style>

        {/* Data Banner */}
        <div className="data-banner">
          <FileSpreadsheet size={15} />
          <span>AI Report from:</span>
          <span className="data-banner-file">{uploadedData.fileName}</span>
          <span className="data-banner-meta">
            · {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.model || 'Gemini-2.5-Flash'}
          </span>
          <Link to="/chat" style={{ marginLeft: 'auto' }}>
            <button className="btn-outline" style={{ fontSize: 11, padding: '4px 10px', gap: 4 }}>
              <MessageSquare size={11} /> Ask AI
            </button>
          </Link>
        </div>

        {/* Header */}
        <div className="page-header">
          <div>
            <h1 className="page-title">AI Report · {uploadedData.fileName}</h1>
            <p className="page-subtitle">
              Generated by {uploadedData.model || 'Gemini-2.5-Flash'} from {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.columns.length} columns
            </p>
          </div>
          <div className="page-actions">
            <Link to="/report/shared">
              <button className="btn-outline" style={{ gap: 6, fontSize: 13 }}>
                <ExternalLink size={13} /> Share Report
              </button>
            </Link>
            <button className="btn-primary" onClick={handleExportPDF} style={{ gap: 6, fontSize: 13 }}>
              <Download size={13} /> Export PDF
            </button>
          </div>
        </div>

        {/* Gemini Unavailability / Fallback Warning Banner */}
        {uploadedData.isGeminiUnavailable && (
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: 12,
            padding: '12px 18px',
            background: 'rgba(245, 158, 11, 0.1)',
            border: '1px solid rgba(245, 158, 11, 0.25)',
            borderRadius: 10,
            marginBottom: 20,
            color: '#f59e0b',
            fontSize: 14,
            fontWeight: 500
          }}>
            <AlertTriangle size={18} style={{ flexShrink: 0 }} />
            <span>{uploadedData.geminiError || "AI insights are temporarily unavailable due to Gemini server load. Local analytics are still available."}</span>
          </div>
        )}

        {/* Executive Summary Banner */}
        <div className="report-hero animate-fadeInUp">
          <div className="report-meta">
            <span className="badge badge-blue"><FileText size={11} /> AI Generated</span>
            <span className="badge badge-green"><CheckCircle2 size={11} /> Auto-analyzed</span>
            <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>
              File: {uploadedData.fileName} · {uploadedData.rowCount.toLocaleString()} rows · {uploadedData.model || 'Gemini-2.5-Flash'}
            </span>
          </div>
          <h2 className="report-title">{uploadedData.datasetType} Analysis Report</h2>
          <p className="report-summary">{uploadedData.summary}</p>
        </div>

        {/* Dynamic KPIs Section */}
        {uploadedData.kpis?.length > 0 && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.15s' }}>
            <div className="report-section-title">
              <CheckCircle2 size={18} color="var(--blue-400)" />
              Calculated KPIs
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16 }}>
              {uploadedData.kpis.map(k => (
                <div key={k.label} style={{ padding: '12px 16px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)' }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 4 }}>{k.label}</div>
                  <div style={{ fontSize: 18, fontWeight: 800, color: 'var(--text-primary)' }}>{k.value}</div>
                  <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 2 }}>{k.desc}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Data Quality Section */}
        {uploadedData.dataQuality && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.18s', marginTop: 20 }}>
            <div className="report-section-title">
              <Activity size={18} color="var(--blue-400)" />
              Dataset Quality & Completeness Audit
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 }}>
              <div style={{ padding: '12px 14px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 8 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Completeness Rate</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: 'var(--blue-400)', marginTop: 4 }}>{uploadedData.dataQuality.completeness}%</div>
              </div>
              <div style={{ padding: '12px 14px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 8 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Quality Score</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: uploadedData.dataQuality.quality > 90 ? 'var(--success)' : 'var(--warning)', marginTop: 4 }}>{uploadedData.dataQuality.quality}%</div>
              </div>
              <div style={{ padding: '12px 14px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 8 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Empty Mapped Cells</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: uploadedData.dataQuality.emptyCount > 0 ? 'var(--warning)' : 'var(--text-primary)', marginTop: 4 }}>{uploadedData.dataQuality.emptyCount}</div>
              </div>
              <div style={{ padding: '12px 14px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 8 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Duplicates Detected</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: uploadedData.dataQuality.duplicatesCount > 0 ? 'var(--warning)' : 'var(--text-primary)', marginTop: 4 }}>{uploadedData.dataQuality.duplicatesCount}</div>
              </div>
            </div>
          </div>
        )}

        {/* AI Insights Grid */}
        {uploadedData.insights?.length > 0 && (
          <>
            <div style={{ fontSize: 13, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Lightbulb size={14} color="var(--blue-400)" />
              Key Insights from {uploadedData.model || 'Gemini'}
            </div>
            <div className="insights-grid animate-fadeInUp" style={{ animationDelay: '0.2s' }}>
              {uploadedData.insights.map((text, i) => {
                const { bg, color } = INSIGHT_COLORS[i % INSIGHT_COLORS.length];
                return (
                  <div key={i} className="insight-card" style={{ animationDelay: `${i * 0.07}s` }}>
                    <div className="insight-icon" style={{ background: bg }}>
                      <TrendingUp size={18} color={color} />
                    </div>
                    <div className="insight-label">Insight {i + 1}</div>
                    <div className="insight-desc">{text}</div>
                  </div>
                );
              })}
            </div>
          </>
        )}

        {/* Charts */}
        {(uploadedData.trendData?.length > 0 || uploadedData.chartData?.length > 0) && (
          <div className="chart-grid animate-fadeInUp" style={{ animationDelay: '0.25s' }}>
            {uploadedData.trendData?.length > 0 && (
              <div className="chart-card">
                <div className="chart-card-header">
                  <div>
                    <div className="chart-card-title">Trend over Time</div>
                    <div className="chart-card-subtitle">From {uploadedData.fileName}</div>
                  </div>
                </div>
                <RevenueAreaChart data={uploadedData.trendData} />
              </div>
            )}
            <div className="chart-card">
              <div className="chart-card-header">
                <div>
                  <div className="chart-card-title">Breakdown Overview</div>
                  <div className="chart-card-subtitle">AI-extracted segments</div>
                </div>
              </div>
              {uploadedData.categoryColExists ? (
                <CategoryBarChart data={uploadedData.chartData} />
              ) : (
                <div style={{
                  height: 240,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'var(--text-muted)',
                  fontSize: 14,
                  border: '1px dashed var(--border-subtle)',
                  borderRadius: 8,
                  margin: '0 20px 20px 20px',
                  background: 'rgba(255, 255, 255, 0.01)'
                }}>
                  Category data not available in the dataset.
                </div>
              )}
            </div>
          </div>
        )}

        {/* AI Recommendations */}
        {uploadedData.recommendations?.length > 0 && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.3s' }}>
            <div className="report-section-title">
              <Target size={18} color="var(--blue-400)" />
              {uploadedData.model || 'Gemini'} Recommendations
            </div>
            <div className="recommendations-list">
              {uploadedData.recommendations.map((r, i) => (
                <div key={i} className="recommendation-item">
                  <div className="recommendation-num">{i + 1}</div>
                  <div>
                    <div className="recommendation-title">{r.title}</div>
                    <div className="recommendation-desc">{r.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Risks & Weaknesses */}
        {((uploadedData.risks && uploadedData.risks.length > 0) || (uploadedData.weaknesses && uploadedData.weaknesses.length > 0)) && (
          <div className="chart-grid animate-fadeInUp" style={{ gridTemplateColumns: '1fr 1fr', animationDelay: '0.35s' }}>
            <div className="chart-card">
              <div className="chart-card-header" style={{ marginBottom: 12 }}>
                <div className="chart-card-title" style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--danger)', fontSize: 16 }}>
                  <AlertTriangle size={18} />
                  Risks & Threats
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {uploadedData.risks?.map((r, i) => (
                  <div key={i} style={{ fontSize: 13, color: 'var(--text-secondary)', padding: '10px 12px', background: 'rgba(239,68,68,0.02)', border: '1px solid rgba(239,68,68,0.1)', borderRadius: 6 }}>
                    {r}
                  </div>
                ))}
              </div>
            </div>

            <div className="chart-card">
              <div className="chart-card-header" style={{ marginBottom: 12 }}>
                <div className="chart-card-title" style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#f59e0b', fontSize: 16 }}>
                  <AlertCircle size={18} />
                  Weaknesses
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {uploadedData.weaknesses?.map((w, i) => (
                  <div key={i} style={{ fontSize: 13, color: 'var(--text-secondary)', padding: '10px 12px', background: 'rgba(245,158,11,0.02)', border: '1px solid rgba(245,158,11,0.1)', borderRadius: 6 }}>
                    {w}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Strengths & Future Opportunities */}
        {((uploadedData.strengths && uploadedData.strengths.length > 0) || (uploadedData.opportunities && uploadedData.opportunities.length > 0)) && (
          <div className="chart-grid animate-fadeInUp" style={{ gridTemplateColumns: '1fr 1fr', animationDelay: '0.4s', marginTop: 20 }}>
            <div className="chart-card">
              <div className="chart-card-header" style={{ marginBottom: 12 }}>
                <div className="chart-card-title" style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--success)', fontSize: 16 }}>
                  <CheckCircle2 size={18} />
                  Strengths
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {uploadedData.strengths?.map((s, i) => (
                  <div key={i} style={{ fontSize: 13, color: 'var(--text-secondary)', padding: '10px 12px', background: 'rgba(16,185,129,0.02)', border: '1px solid rgba(16,185,129,0.1)', borderRadius: 6 }}>
                    {s}
                  </div>
                ))}
              </div>
            </div>

            <div className="chart-card">
              <div className="chart-card-header" style={{ marginBottom: 12 }}>
                <div className="chart-card-title" style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--blue-400)', fontSize: 16 }}>
                  <Target size={18} />
                  Future Opportunities
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {uploadedData.opportunities?.map((o, i) => (
                  <div key={i} style={{ fontSize: 13, color: 'var(--text-secondary)', padding: '10px 12px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 6 }}>
                    {o}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* AI Data Anomalies */}
        {uploadedData.anomalies?.length > 0 && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.45s', marginTop: 20 }}>
            <div className="report-section-title">
              <AlertTriangle size={18} color="#ef4444" />
              Data Anomalies & Outliers Scan
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {uploadedData.anomalies.map((anom, i) => (
                <div key={i} style={{ display: 'flex', gap: 12, padding: '16px', background: 'rgba(239,68,68,0.03)', border: '1px solid rgba(239,68,68,0.15)', borderRadius: 'var(--radius-md)' }}>
                  <AlertTriangle size={16} color="#ef4444" style={{ flexShrink: 0, marginTop: 2 }} />
                  <span style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{anom}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Conclusion Section */}
        {uploadedData.conclusion && (
          <div className="report-section animate-fadeInUp" style={{ animationDelay: '0.5s', marginTop: 20 }}>
            <div className="report-section-title">
              <FileText size={18} color="var(--blue-400)" />
              Conclusion
            </div>
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
              {uploadedData.conclusion}
            </p>
          </div>
        )}

        {/* Dataset Overview */}
        <div className="report-section animate-fadeInUp" style={{ marginTop: 20, animationDelay: '0.55s' }}>
          <div className="report-section-title">
            <BarChart2 size={18} color="var(--blue-400)" />
            Dataset Overview
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16, marginBottom: 16 }}>
            {[
              { label: 'Total Rows',    value: uploadedData.rowCount.toLocaleString() },
              { label: 'Columns',       value: uploadedData.columns.length },
              { label: 'File',          value: uploadedData.fileName },
            ].map(({ label, value }) => (
              <div key={label} style={{ padding: '14px 18px', background: 'var(--bg-glass-light)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)' }}>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>{label}</div>
                <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--text-primary)' }}>{value}</div>
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {uploadedData.columns.map(col => (
              <span key={col} className="column-badge">{col}</span>
            ))}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="footer-actions" style={{ display: 'flex', gap: 12, justifyContent: 'flex-end', marginTop: 8, paddingBottom: 24 }}>
          <Link to="/report/shared">
            <button className="btn-outline" style={{ gap: 6 }}>
              <Share2 size={14} /> Share as Live Link
            </button>
          </Link>
          <button className="btn-primary" onClick={handleDownloadReportText} style={{ gap: 6 }}>
            <Download size={14} /> Download Full Report
          </button>
        </div>

      </main>
    </div>
  );
}